apiVersion: v1
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "secrets/**.pem" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}
  namespace: polaris-system
type: Opaque