apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: polaris-sidecar-injector
  namespace: polaris-system
  labels:
    app: sidecar-injector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sidecar-injector