apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  labels:
    k8s-app: polaris-controller
  name: polaris-controller-metrics
  namespace: polaris-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: polaris-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}