apiVersion: v1
kind: Service
metadata:
  name: {{ include "polaris-controller.controller.fullname" . }}-injector
  namespace: polaris-system
  labels:
    app: sidecar-injector
spec:
  ports:
    - port: {{ .Values.sidecar.port }}
      targetPort: 9443
  selector:
    {{- include "polaris-controller.controller.selectorLabels" . | nindent 4 }}